import type { BibleVerse, VerseSuggestion, KICDPlan } from "./planner-types"

export const GRADES = ["PP1", "PP2", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8", "Grade 9"]

export const DURATIONS = ["30", "35", "40", "45", "50", "60", "80", "90", "120"]

export const TERMS = ["Term 1", "Term 2", "Term 3"]

export const LESSON_NUMBERS = Array.from({ length: 30 }, (_, i) => String(i + 1))

export const LEARNING_AREAS_BY_GRADE: Record<string, string[]> = {
  PP1: ["Language Activities", "Mathematical Activities", "Environmental Activities", "Psychomotor and Creative Activities", "Religious Education Activities"],
  PP2: ["Language Activities", "Mathematical Activities", "Environmental Activities", "Psychomotor and Creative Activities", "Religious Education Activities"],
  "Grade 1": ["Literacy", "Kiswahili", "English", "Mathematics", "Environmental Activities", "Hygiene and Nutrition", "Religious Education", "Movement and Creative Activities"],
  "Grade 2": ["Literacy", "Kiswahili", "English", "Mathematics", "Environmental Activities", "Hygiene and Nutrition", "Religious Education", "Movement and Creative Activities"],
  "Grade 3": ["Literacy", "Kiswahili", "English", "Mathematics", "Environmental Activities", "Hygiene and Nutrition", "Religious Education", "Movement and Creative Activities"],
  "Grade 4": ["English", "Kiswahili", "Mathematics", "Science and Technology", "Social Studies", "Religious Education", "Creative Arts", "Physical and Health Education", "Agriculture"],
  "Grade 5": ["English", "Kiswahili", "Mathematics", "Science and Technology", "Social Studies", "Religious Education", "Creative Arts", "Physical and Health Education", "Agriculture"],
  "Grade 6": ["English", "Kiswahili", "Mathematics", "Science and Technology", "Social Studies", "Religious Education", "Creative Arts", "Physical and Health Education", "Agriculture"],
  "Grade 7": ["English", "Kiswahili", "Mathematics", "Integrated Science", "Social Studies", "Religious Education", "Creative Arts and Sports", "Health Education", "Pre-Technical and Career Studies", "Agriculture and Nutrition"],
  "Grade 8": ["English", "Kiswahili", "Mathematics", "Integrated Science", "Social Studies", "Religious Education", "Creative Arts and Sports", "Health Education", "Pre-Technical and Career Studies", "Agriculture and Nutrition"],
  "Grade 9": ["English", "Kiswahili", "Mathematics", "Integrated Science", "Social Studies", "Religious Education", "Creative Arts and Sports", "Health Education", "Pre-Technical and Career Studies", "Agriculture and Nutrition"],
}

export const STRANDS_BY_AREA: Record<string, string[]> = {
  Mathematics: ["Numbers", "Measurement", "Geometry", "Algebra", "Data Handling", "Patterns and Sequences"],
  English: ["Listening and Speaking", "Reading", "Writing", "Grammar", "Comprehension"],
  Kiswahili: ["Kusikiliza na Kuzungumza", "Kusoma", "Kuandika", "Sarufi", "Msamiati"],
  "Science and Technology": ["Living Things", "Environment", "Energy", "Force and Motion", "Materials", "Technology"],
  "Integrated Science": ["Scientific Investigation", "Living Things and Environment", "Energy and Motion", "Matter and Materials", "Health and Safety"],
  "Social Studies": ["People and Relationships", "Resources and Economic Activities", "Political Systems and Governance", "Peace and Conflict Resolution", "Environment and Natural Resources"],
  "Religious Education": ["Creation", "Faith and Beliefs", "Moral Values", "Worship and Rituals", "Community Life"],
  "Creative Arts": ["Visual Arts", "Music", "Drama and Theatre", "Dance", "Craft"],
  "Creative Arts and Sports": ["Visual Arts", "Music", "Drama and Theatre", "Dance and Movement", "Sports and Games"],
  "Physical and Health Education": ["Locomotor Skills", "Non-locomotor Skills", "Manipulative Skills", "Health and Hygiene", "Safety"],
  Agriculture: ["Soil", "Plants", "Animals", "Farm Tools", "Food Production"],
  "Agriculture and Nutrition": ["Soil and Water Conservation", "Crop Production", "Animal Production", "Food and Nutrition", "Entrepreneurship"],
  "Environmental Activities": ["Environment", "Weather", "Plants", "Animals", "Water"],
  "Hygiene and Nutrition": ["Personal Hygiene", "Food and Nutrition", "Safety", "Community Health"],
  Literacy: ["Listening", "Speaking", "Reading", "Writing", "Language Structure"],
  "Language Activities": ["Listening", "Speaking", "Pre-reading", "Pre-writing", "Language Skills"],
  "Mathematical Activities": ["Number Work", "Measurement", "Geometry", "Patterns", "Data"],
  "Psychomotor and Creative Activities": ["Gross Motor Skills", "Fine Motor Skills", "Creative Play", "Art and Craft", "Music and Movement"],
  "Religious Education Activities": ["God and Me", "My Family", "My Community", "Celebrations", "Nature"],
  "Movement and Creative Activities": ["Locomotor Skills", "Non-locomotor Skills", "Creative Expression", "Games", "Swimming"],
  "Pre-Technical and Career Studies": ["Technical Skills", "Career Awareness", "Entrepreneurship", "Technology", "Safety"],
  "Health Education": ["Personal Health", "Nutrition", "Disease Prevention", "Reproductive Health", "Substance Abuse"],
}

export const SUBSTRANDS: Record<string, string[]> = {
  Numbers: ["Number Concepts", "Counting", "Place Value", "Addition", "Subtraction", "Multiplication", "Division", "Fractions", "Decimals", "Percentages", "Integers", "Ratios and Proportions"],
  Measurement: ["Length", "Mass", "Capacity", "Time", "Money", "Perimeter", "Area", "Volume", "Temperature"],
  Geometry: ["Basic Shapes", "2D Shapes", "3D Shapes", "Position and Direction", "Symmetry", "Angles", "Lines", "Tessellation"],
  Algebra: ["Patterns", "Sequences", "Algebraic Expressions", "Equations", "Inequalities"],
  "Data Handling": ["Data Collection", "Data Representation", "Data Interpretation", "Probability"],
  "Patterns and Sequences": ["Number Patterns", "Shape Patterns", "Growing Patterns", "Repeating Patterns"],
  "Listening and Speaking": ["Pronunciation", "Oral Narratives", "Conversations", "Dictation", "Public Speaking"],
  Reading: ["Phonics", "Fluency", "Vocabulary", "Comprehension", "Reading Aloud"],
  Writing: ["Handwriting", "Spelling", "Sentence Construction", "Paragraph Writing", "Creative Writing", "Letter Writing"],
  Grammar: ["Nouns", "Verbs", "Adjectives", "Adverbs", "Tenses", "Sentence Structure", "Punctuation"],
  Comprehension: ["Literal Comprehension", "Inferential Comprehension", "Critical Comprehension", "Summarizing"],
  "Kusikiliza na Kuzungumza": ["Matamshi", "Simulizi", "Mazungumzo", "Imla", "Hotuba"],
  Kusoma: ["Foniki", "Usawa wa Kusoma", "Msamiati", "Ufahamu", "Kusoma kwa Sauti"],
  Kuandika: ["Mwandiko", "Tahajia", "Uundaji wa Sentensi", "Insha", "Barua"],
  Sarufi: ["Nomino", "Vitenzi", "Vivumishi", "Vielezi", "Nyakati", "Muundo wa Sentensi"],
  Msamiati: ["Msamiati wa Msingi", "Msamiati wa Mazingira", "Msamiati wa Shule", "Msamiati wa Nyumbani"],
  "Living Things": ["Plants", "Animals", "Human Body", "Life Cycles", "Habitats", "Classification"],
  Environment: ["Weather", "Soil", "Water", "Air", "Pollution", "Conservation"],
  Energy: ["Forms of Energy", "Light", "Sound", "Heat", "Electricity", "Renewable Energy"],
  "Force and Motion": ["Push and Pull", "Gravity", "Friction", "Magnetism", "Simple Machines"],
  Materials: ["Properties of Materials", "States of Matter", "Changes in Materials", "Uses of Materials"],
  Technology: ["Simple Tools", "Computers", "Communication Technology", "Transport Technology"],
  "Scientific Investigation": ["Observation", "Measurement", "Experimentation", "Data Recording", "Conclusion"],
  "Living Things and Environment": ["Cells", "Tissues and Organs", "Ecosystems", "Biodiversity", "Human Body Systems"],
  "Energy and Motion": ["Forms of Energy", "Energy Transfer", "Speed and Velocity", "Newton's Laws of Motion", "Work and Power"],
  "Matter and Materials": ["Atoms and Elements", "Compounds and Mixtures", "Chemical Reactions", "Acids and Bases"],
  "Health and Safety": ["First Aid", "Disease Prevention", "Nutrition", "Personal Safety"],
  "People and Relationships": ["Family", "Community", "Culture", "Conflict Resolution"],
  "Resources and Economic Activities": ["Natural Resources", "Agriculture", "Trade", "Tourism"],
  "Political Systems and Governance": ["Government", "Leadership", "Constitution", "Civic Rights"],
  "Peace and Conflict Resolution": ["Conflict Management", "Peacebuilding", "Human Rights"],
  "Environment and Natural Resources": ["Weather and Climate", "Vegetation", "Wildlife", "Conservation"],
  Creation: ["The Universe", "Human Beings", "Animals and Plants", "Environment"],
  "Faith and Beliefs": ["Belief in God", "Prayer and Worship", "Holy Books", "Religious Practices"],
  "Moral Values": ["Honesty", "Kindness", "Respect", "Responsibility", "Forgiveness"],
  "Worship and Rituals": ["Prayer", "Songs and Hymns", "Sacred Places", "Religious Festivals"],
  "Community Life": ["Family Relationships", "Community Service", "Sharing", "Helping Others"],
  "Visual Arts": ["Drawing", "Painting", "Printmaking", "Sculpture", "Design"],
  Music: ["Singing", "Rhythm", "Musical Instruments", "Melody", "Composition"],
  "Drama and Theatre": ["Role Play", "Puppetry", "Improvisation", "Storytelling"],
  Dance: ["Body Movement", "Traditional Dance", "Creative Dance", "Dance Patterns"],
  "Dance and Movement": ["Body Control", "Creative Dance", "Cultural Dance", "Dance Composition"],
  Craft: ["Paper Craft", "Clay Work", "Weaving", "Beadwork", "Woodwork"],
  "Sports and Games": ["Athletics", "Ball Games", "Gymnastics", "Swimming", "Traditional Games"],
  "Locomotor Skills": ["Walking", "Running", "Jumping", "Hopping", "Skipping", "Galloping"],
  "Non-locomotor Skills": ["Bending", "Stretching", "Twisting", "Balancing", "Pushing", "Pulling"],
  "Manipulative Skills": ["Throwing", "Catching", "Kicking", "Striking", "Dribbling"],
  "Health and Hygiene": ["Hand Washing", "Oral Hygiene", "Cleanliness", "Healthy Eating"],
  Safety: ["Road Safety", "Home Safety", "School Safety", "Fire Safety", "First Aid"],
  Soil: ["Soil Types", "Soil Properties", "Soil Conservation", "Soil Preparation"],
  Plants: ["Plant Parts", "Plant Growth", "Plant Protection", "Crops", "Gardening"],
  Animals: ["Domestic Animals", "Wild Animals", "Animal Care", "Animal Products"],
  "Farm Tools": ["Simple Tools", "Tool Safety", "Tool Maintenance"],
  "Food Production": ["Food Crops", "Food Preservation", "Food Processing", "Food Storage"],
  "Soil and Water Conservation": ["Soil Erosion", "Water Harvesting", "Irrigation", "Conservation Methods"],
  "Crop Production": ["Crop Types", "Planting", "Crop Care", "Harvesting", "Storage"],
  "Animal Production": ["Animal Breeds", "Animal Feeding", "Animal Health", "Housing"],
  "Food and Nutrition": ["Nutrients", "Balanced Diet", "Food Groups", "Meal Planning", "Food Hygiene", "Healthy Eating", "Food Safety", "Meal Times"],
  Entrepreneurship: ["Business Ideas", "Saving", "Budgeting", "Marketing"],
  Weather: ["Weather Conditions", "Weather Symbols", "Weather Instruments", "Seasons"],
  Water: ["Sources of Water", "Uses of Water", "Water Conservation", "Water Treatment"],
  "Personal Hygiene": ["Body Care", "Dental Care", "Hand Washing", "Toilet Use"],
  "Community Health": ["Disease Prevention", "Immunization", "Community Cleanliness"],
  "Language Skills": ["Listening Skills", "Speaking Skills", "Vocabulary", "Communication"],
  "Number Work": ["Counting", "Number Recognition", "Number Writing", "Comparing Numbers", "Shapes"],
  "Pre-reading": ["Visual Discrimination", "Auditory Discrimination", "Letter Recognition", "Phonics"],
  "Pre-writing": ["Tracing", "Maze", "Pattern Writing", "Hand Grip"],
  "Gross Motor Skills": ["Running", "Jumping", "Climbing", "Balancing"],
  "Fine Motor Skills": ["Cutting", "Coloring", "Threading", "Modeling"],
  "Creative Play": ["Pretend Play", "Dramatic Play", "Construction Play"],
  "Art and Craft": ["Drawing", "Painting", "Modeling", "Collage"],
  "Music and Movement": ["Rhythm", "Singing", "Dance", "Action Songs"],
  "God and Me": ["God's Creation", "Myself", "My Senses", "My Feelings"],
  "My Family": ["Family Members", "Family Roles", "Family Values"],
  "My Community": ["Community Helpers", "Places in Community", "Cultural Practices"],
  Celebrations: ["Birthdays", "Religious Celebrations", "National Holidays"],
  Nature: ["Plants and Animals", "Weather", "Water", "Environment Care"],
  "Technical Skills": ["Basic Tools", "Measurement", "Drawing", "Modeling", "Material Handling", "Tool Use"],
  "Career Awareness": ["Career Exploration", "Skills for Work", "Work Ethics"],
  "Personal Health": ["Hygiene", "Physical Fitness", "Mental Health", "Healthy Lifestyle"],
  Nutrition: ["Food Groups", "Balanced Diet", "Meal Planning", "Food Safety"],
  "Disease Prevention": ["Common Diseases", "Immunization", "Healthy Practices"],
  "Reproductive Health": ["Adolescence", "Body Changes", "Personal Care"],
  "Substance Abuse": ["Drug Awareness", "Peer Pressure", "Healthy Choices"],
}

export const OUTCOMES_BY_SUBSTRAND: Record<string, string[]> = {
  "Number Concepts": [
    "Learners identify and count objects up to 100",
    "Learners read and write numbers in symbols and words",
    "Learners compare and order numbers using place value",
    "Learners represent numbers using concrete objects and pictures",
  ],
  Counting: [
    "Learners count forward and backward from any number",
    "Learners skip count in 2s, 5s, and 10s",
    "Learners estimate quantities and verify by counting",
  ],
  "Place Value": [
    "Learners identify place value of digits up to hundreds",
    "Learners decompose numbers into tens and ones",
    "Learners compose numbers using place value",
  ],
  Addition: [
    "Learners solve simple addition problems using objects",
    "Learners add numbers without regrouping up to 100",
    "Learners apply addition in real-life situations involving money",
  ],
  Subtraction: [
    "Learners solve subtraction problems using concrete objects",
    "Learners subtract numbers without regrouping up to 100",
    "Learners apply subtraction in real-life contexts",
  ],
  Multiplication: [
    "Learners understand multiplication as repeated addition",
    "Learners multiply single-digit numbers using skip counting",
    "Learners solve multiplication word problems",
  ],
  Division: [
    "Learners understand division as equal sharing",
    "Learners divide numbers using concrete objects",
    "Learners solve simple division word problems",
  ],
  Fractions: [
    "Learners identify halves, thirds, and quarters of objects",
    "Learners represent fractions using diagrams",
    "Learners compare simple fractions in real-life contexts",
  ],
  Decimals: [
    "Learners identify decimal notation in money and measurement",
    "Learners add and subtract decimals in money contexts",
  ],
  Percentages: [
    "Learners describe percentage as part of a hundred",
    "Learners calculate simple percentages in real-life contexts",
  ],
  Length: [
    "Learners measure length using non-standard units",
    "Learners measure length in metres and centimetres",
    "Learners estimate and compare lengths of objects",
  ],
  Mass: [
    "Learners compare mass using a balance scale",
    "Learners measure mass in kilograms and grams",
    "Learners estimate mass of common objects",
  ],
  Capacity: [
    "Learners compare capacity of containers",
    "Learners measure capacity in litres",
    "Learners estimate capacity in everyday contexts",
  ],
  Time: [
    "Learners tell time in hours and half-hours",
    "Learners read a calendar and identify days, weeks, months",
    "Learners sequence events using time vocabulary",
  ],
  Money: [
    "Learners identify Kenyan currency notes and coins",
    "Learners count money in shillings and cents",
    "Learners solve problems involving buying and selling",
  ],
  Pronunciation: [
    "Learners pronounce sounds and words correctly",
    "Learners identify letter sounds and blend them to form words",
  ],
  Conversations: [
    "Learners initiate and sustain simple conversations",
    "Learners use appropriate greetings and polite language",
    "Learners express ideas clearly in group discussions",
  ],
  "Oral Narratives": [
    "Learners retell simple stories with sequence",
    "Learners create and tell original stories",
    "Learners identify main ideas in oral narratives",
  ],
  "Literal Comprehension": [
    "Learners answer factual questions about a text",
    "Learners identify main ideas explicitly stated in a passage",
    "Learners recall details from a story or article",
  ],
  "Inferential Comprehension": [
    "Learners make predictions based on textual clues",
    "Learners draw conclusions from a text",
    "Learners infer character feelings and motives",
  ],
  "Sentence Construction": [
    "Learners construct grammatically correct sentences",
    "Learners use proper punctuation in sentences",
    "Learners expand simple sentences using adjectives",
  ],
  "Creative Writing": [
    "Learners write short paragraphs on familiar topics",
    "Learners compose simple poems and stories",
    "Learners organize ideas logically in writing",
  ],
  Family: [
    "Learners describe roles of different family members",
    "Learners appreciate the importance of family unity",
    "Learners demonstrate responsibility in family tasks",
  ],
  Community: [
    "Learners identify various community helpers",
    "Learners describe services provided by community members",
    "Learners participate in community service activities",
  ],
  Culture: [
    "Learners describe cultural practices in their community",
    "Learners appreciate diverse cultural traditions",
    "Learners participate in cultural events and festivals",
  ],
  "Natural Resources": [
    "Learners identify natural resources in their locality",
    "Learners describe uses of natural resources",
    "Learners practice conservation of natural resources",
  ],
  Plants: [
    "Learners identify common plants in the environment",
    "Learners describe parts of a plant and their functions",
    "Learners grow plants and record their growth",
    "Learners appreciate the importance of plants",
  ],
  Animals: [
    "Learners identify common animals and their habitats",
    "Learners classify animals according to characteristics",
    "Learners describe how animals are useful to humans",
  ],
  "Human Body": [
    "Learners identify parts of the human body",
    "Learners describe functions of sense organs",
    "Learners practice good hygiene for body care",
  ],
  Environment: [
    "Learners describe ways to care for the environment",
    "Learners identify sources of water and their uses",
    "Learners sort waste for proper disposal",
  ],
  Energy: [
    "Learners identify sources of energy in daily life",
    "Learners describe uses of light, heat, and sound",
    "Learners practice safety when using electrical appliances",
  ],
  "Belief in God": [
    "Learners express understanding of God as the creator",
    "Learners appreciate God's love and care",
    "Learners demonstrate gratitude through prayer",
  ],
  Honesty: [
    "Learners demonstrate honesty in words and actions",
    "Learners tell the truth even when it is difficult",
    "Learners return items that do not belong to them",
  ],
  Drawing: [
    "Learners draw objects from the environment",
    "Learners use different drawing materials creatively",
    "Learners express ideas through drawing",
  ],
  Singing: [
    "Learners sing songs with correct melody and rhythm",
    "Learners sing patriotic and religious songs",
    "Learners use songs to express emotions and ideas",
  ],
  Gardening: [
    "Learners prepare a garden for planting",
    "Learners plant and care for vegetables",
    "Learners harvest and use farm produce",
  ],
}

export const TEACHER_ACTIVITIES = [
  "Guides learners through examples using real objects",
  "Demonstrates concepts using practical activities",
  "Asks probing questions to promote critical thinking",
  "Supervises group activities and provides support",
  "Provides feedback during and after tasks",
  "Facilitates class discussion on key concepts",
  "Models correct pronunciation and language use",
  "Uses charts and visual aids to explain content",
  "Moves around the class to monitor progress",
  "Differentiates instruction for diverse learners",
  "Gives clear instructions for each learning task",
  "Encourages learners to share their ideas",
  "Uses songs, rhymes, and games to reinforce learning",
  "Conducts demonstration experiments",
  "Provides remediation for learners needing extra support",
]

export const LEARNER_ACTIVITIES = [
  "Works in groups to solve problems and tasks",
  "Answers oral questions during class discussion",
  "Completes worksheets and written exercises",
  "Participates actively in class discussions",
  "Presents group findings to the class",
  "Engages in hands-on practical activities",
  "Practices skills individually and in pairs",
  "Sings songs and recites rhymes",
  "Plays educational games related to the topic",
  "Observes demonstrations and takes notes",
  "Draws and labels diagrams in exercise books",
  "Reads aloud and silently from texts",
  "Measures and records data from experiments",
  "Creates models and projects using available materials",
  "Peer-assesses and self-assesses their work",
]

export const RESOURCES = [
  "Textbooks",
  "Flashcards",
  "Real objects (realia)",
  "Charts and posters",
  "Worksheets",
  "Digital devices (tablets/laptops)",
  "Classroom environment",
  "Manipulatives (counting beads, blocks)",
  "Songs and audio recordings",
  "Library books",
  "Science equipment",
  "Art and craft materials",
  "Sports equipment",
  "Models and specimens",
  "Weather instruments",
  "Clay and modelling materials",
  "Puppets and props",
  "Wall maps and globes",
]

export const ASSESSMENT_METHODS = [
  "Observation",
  "Oral questioning",
  "Written exercise",
  "Group presentation",
  "Practical demonstration",
  "Portfolio assessment",
  "Peer assessment",
  "Self-assessment",
  "Project work",
  "Checklist assessment",
  "Anecdotal records",
  "Quiz",
]

export const REMARKS = [
  "Lesson well received. Learners demonstrated understanding.",
  "Most learners achieved expected competency level.",
  "Some learners need reinforcement in key areas.",
  "Excellent participation and engagement observed.",
  "Learners enjoyed the activities and participated actively.",
  "Lesson proceeded as planned. All objectives achieved.",
  "Majority of learners grasped the concept with minimal support.",
  "Learners showed great creativity and critical thinking.",
  "Some learners required additional scaffolding during tasks.",
  "Very interactive lesson with high learner engagement.",
]

export const coreCompetencies = [
  "Communication and Collaboration",
  "Critical Thinking and Problem Solving",
  "Creativity and Imagination",
  "Citizenship",
  "Digital Literacy",
  "Learning to Learn",
  "Self-Efficacy",
]

export const values = [
  "Love",
  "Responsibility",
  "Respect",
  "Unity",
  "Peace",
  "Integrity",
  "Patriotism",
]

export const pciOptions = [
  "Life Skills and Values Education",
  "Health Education",
  "Environmental Education",
  "Citizenship Education",
  "Peace Education",
  "Safety and Security Education",
  "Gender Issues in Education",
  "Drug and Substance Abuse Awareness",
  "Child Rights and Child Protection",
  "HIV and AIDS Education",
  "Parental Empowerment and Engagement",
  "Career Guidance and Mentorship",
]

export const SUBSTRAND_COMPETENCY_MAP: Record<string, string[]> = {
  "Number Concepts": ["Critical Thinking and Problem Solving"],
  Counting: ["Critical Thinking and Problem Solving"],
  "Place Value": ["Critical Thinking and Problem Solving", "Digital Literacy"],
  Addition: ["Critical Thinking and Problem Solving", "Self-Efficacy"],
  Subtraction: ["Critical Thinking and Problem Solving", "Self-Efficacy"],
  Multiplication: ["Critical Thinking and Problem Solving", "Self-Efficacy"],
  Division: ["Critical Thinking and Problem Solving", "Self-Efficacy"],
  Fractions: ["Critical Thinking and Problem Solving", "Creativity and Imagination"],
  Length: ["Critical Thinking and Problem Solving", "Digital Literacy"],
  Mass: ["Critical Thinking and Problem Solving", "Digital Literacy"],
  Capacity: ["Critical Thinking and Problem Solving", "Digital Literacy"],
  Time: ["Critical Thinking and Problem Solving", "Digital Literacy"],
  Money: ["Critical Thinking and Problem Solving", "Self-Efficacy", "Citizenship"],
  "Listening and Speaking": ["Communication and Collaboration", "Creativity and Imagination"],
  Conversations: ["Communication and Collaboration", "Citizenship"],
  Reading: ["Communication and Collaboration", "Learning to Learn"],
  "Sentence Construction": ["Communication and Collaboration", "Creativity and Imagination"],
  "Creative Writing": ["Creativity and Imagination", "Communication and Collaboration", "Self-Efficacy"],
  Plants: ["Creativity and Imagination", "Critical Thinking and Problem Solving", "Digital Literacy"],
  Animals: ["Creativity and Imagination", "Critical Thinking and Problem Solving"],
  "Human Body": ["Self-Efficacy", "Learning to Learn"],
  Environment: ["Citizenship", "Critical Thinking and Problem Solving"],
  Energy: ["Critical Thinking and Problem Solving", "Digital Literacy"],
  Family: ["Citizenship", "Communication and Collaboration"],
  Community: ["Citizenship", "Communication and Collaboration"],
  Culture: ["Citizenship", "Creativity and Imagination"],
  "Belief in God": ["Citizenship", "Self-Efficacy"],
  Honesty: ["Communication and Collaboration", "Citizenship"],
  Drawing: ["Creativity and Imagination", "Self-Efficacy"],
  Singing: ["Creativity and Imagination", "Communication and Collaboration"],
  Gardening: ["Self-Efficacy", "Creativity and Imagination", "Citizenship"],
  "Natural Resources": ["Citizenship", "Critical Thinking and Problem Solving", "Digital Literacy"],
}

export const SUBSTRAND_VALUE_MAP: Record<string, string[]> = {
  Family: ["Love", "Respect", "Responsibility", "Unity"],
  Community: ["Respect", "Unity", "Responsibility", "Peace"],
  "Belief in God": ["Love", "Respect", "Integrity"],
  Honesty: ["Integrity", "Respect", "Responsibility"],
  Environment: ["Responsibility", "Respect", "Love"],
  "Natural Resources": ["Responsibility", "Respect", "Patriotism"],
  Culture: ["Unity", "Respect", "Peace", "Love"],
  Money: ["Integrity", "Responsibility"],
  Energy: ["Responsibility", "Peace"],
  Plants: ["Responsibility", "Love", "Respect"],
  Animals: ["Responsibility", "Love", "Respect"],
  Gardening: ["Responsibility", "Patriotism", "Love"],
  "Place Value": ["Responsibility", "Self-Efficacy"],
}

export const SUBSTRAND_PCI_MAP: Record<string, string[]> = {
  Environment: ["Environmental Education", "Health Education"],
  "Natural Resources": ["Environmental Education", "Citizenship Education"],
  Energy: ["Environmental Education", "Safety and Security Education"],
  "Health and Hygiene": ["Health Education", "Life Skills and Values Education"],
  Safety: ["Safety and Security Education", "Life Skills and Values Education"],
  "Human Body": ["Health Education", "Life Skills and Values Education"],
  "Community Health": ["Health Education", "Citizenship Education"],
  "Drug and Substance Abuse": ["Drug and Substance Abuse Awareness", "Health Education"],
  Family: ["Life Skills and Values Education", "Child Rights and Child Protection"],
  Culture: ["Citizenship Education", "Peace Education"],
  Community: ["Citizenship Education", "Life Skills and Values Education"],
  "Road Safety": ["Safety and Security Education", "Life Skills and Values Education"],
  Plants: ["Environmental Education"],
  Animals: ["Environmental Education"],
  Gardening: ["Environmental Education", "Career Guidance and Mentorship"],
  Money: ["Life Skills and Values Education", "Parental Empowerment and Engagement"],
}

export const STRAND_FALLBACK_OUTCOMES: Record<string, string[]> = {
  Numbers: [
    "Learners identify and manipulate numbers in various contexts",
    "Learners apply number operations to solve real-life problems",
    "Learners demonstrate understanding of number relationships",
  ],
  Measurement: [
    "Learners use appropriate units to measure different attributes",
    "Learners estimate and compare measurements in daily contexts",
    "Learners apply measurement skills in practical activities",
  ],
  Geometry: [
    "Learners identify and describe geometric shapes in the environment",
    "Learners explore spatial relationships and properties of shapes",
    "Learners create and interpret geometric patterns",
  ],
  Algebra: [
    "Learners recognize and extend patterns in various contexts",
    "Learners use symbols to represent mathematical relationships",
    "Learners solve simple equations using logical reasoning",
  ],
  "Data Handling": [
    "Learners collect and organize data from their environment",
    "Learners represent data using simple graphs and charts",
    "Learners interpret data to make informed decisions",
  ],
  "Listening and Speaking": [
    "Learners demonstrate active listening in various communication contexts",
    "Learners express ideas clearly using appropriate vocabulary",
    "Learners engage in meaningful conversations with peers and adults",
  ],
  Reading: [
    "Learners read grade-appropriate texts with fluency and comprehension",
    "Learners identify main ideas and supporting details in texts",
    "Learners develop vocabulary through contextual reading",
  ],
  Writing: [
    "Learners write coherent sentences and paragraphs on familiar topics",
    "Learners apply correct grammar and punctuation in writing",
    "Learners organize ideas logically in written compositions",
  ],
  Grammar: [
    "Learners identify and use parts of speech correctly",
    "Learners construct grammatically correct sentences",
    "Learners apply language conventions in written and oral communication",
  ],
  Comprehension: [
    "Learners demonstrate understanding of both fiction and non-fiction texts",
    "Learners make predictions and draw conclusions from texts",
    "Learners analyze characters, settings, and events in stories",
  ],
  Environment: [
    "Learners describe the importance of environmental conservation",
    "Learners identify environmental threats in their locality",
    "Learners suggest practical solutions to protect the environment",
  ],
  Energy: [
    "Learners identify different forms of energy in daily life",
    "Learners describe how energy is used in homes and industry",
    "Learners practice energy conservation and safety measures",
  ],
  "Living Things": [
    "Learners identify living and non-living things in the environment",
    "Learners describe characteristics and life processes of organisms",
    "Learners appreciate biodiversity and the need for conservation",
  ],
  Plants: [
    "Learners identify common plants in their locality",
    "Learners describe the importance of plants to humans and animals",
    "Learners demonstrate proper plant care and conservation practices",
  ],
  Animals: [
    "Learners identify common animals and their habitats",
    "Learners classify animals based on observable characteristics",
    "Learners describe the importance of animals to human life",
  ],
  "People and Relationships": [
    "Learners identify different types of relationships in society",
    "Learners demonstrate respect and empathy in interactions",
    "Learners resolve conflicts peacefully using dialogue",
  ],
  "Resources and Economic Activities": [
    "Learners identify natural resources in their community",
    "Learners describe various economic activities in the locality",
    "Learners practice responsible use of community resources",
  ],
  "Political Systems and Governance": [
    "Learners describe the structure of leadership in the community",
    "Learners explain the importance of rules and laws",
    "Learners demonstrate good citizenship in school and community",
  ],
  "Peace and Conflict Resolution": [
    "Learners identify causes of conflict in daily situations",
    "Learners apply conflict resolution strategies peacefully",
    "Learners promote harmony and coexistence in diverse settings",
  ],
  "Visual Arts": [
    "Learners explore different art materials and techniques",
    "Learners create artistic works inspired by the environment",
    "Learners express ideas and emotions through visual art",
  ],
  Music: [
    "Learners identify elements of music including rhythm and melody",
    "Learners sing and perform simple musical pieces",
    "Learners appreciate music from different cultures",
  ],
  "Drama and Theatre": [
    "Learners participate in dramatic activities and role play",
    "Learners express ideas through body movement and dialogue",
    "Learners develop confidence through public performance",
  ],
  Dance: [
    "Learners perform basic dance movements and sequences",
    "Learners create simple dance routines individually and in groups",
    "Learners appreciate dance as a form of cultural expression",
  ],
  "Locomotor Skills": [
    "Learners demonstrate fundamental locomotor movements correctly",
    "Learners combine locomotor skills in games and activities",
    "Learners develop coordination and body awareness through movement",
  ],
  "Non-locomotor Skills": [
    "Learners demonstrate balance and stability in various positions",
    "Learners perform bending, stretching, and twisting movements",
    "Learners control body movements during physical activities",
  ],
  "Manipulative Skills": [
    "Learners demonstrate throwing, catching, and kicking skills",
    "Learners manipulate objects with increasing control and accuracy",
    "Learners apply manipulative skills in games and sports",
  ],
  "Health and Hygiene": [
    "Learners practice proper personal hygiene routines daily",
    "Learners explain the importance of cleanliness for health",
    "Learners demonstrate healthy habits in school and at home",
  ],
  Safety: [
    "Learners identify potential safety hazards in different environments",
    "Learners apply safety rules at home, school, and on the road",
    "Learners demonstrate basic first aid and emergency response",
  ],
  Soil: [
    "Learners identify different soil types in the locality",
    "Learners describe the importance of soil for plant growth",
    "Learners practice soil conservation techniques",
  ],
  "Food Production": [
    "Learners identify food crops grown in the community",
    "Learners describe methods of food preservation and storage",
    "Learners appreciate the value of agriculture in daily life",
  ],
  "Food and Nutrition": [
    "Learners classify foods into different food groups",
    "Learners plan balanced meals for healthy living",
    "Learners practice proper food hygiene and safety",
  ],
  Entrepreneurship: [
    "Learners identify business opportunities in the community",
    "Learners develop basic entrepreneurial and financial skills",
    "Learners demonstrate responsible use of money and resources",
  ],
  Weather: [
    "Learners observe and describe different weather conditions",
    "Learners record weather data using simple instruments",
    "Learners explain how weather affects daily activities",
  ],
  Water: [
    "Learners identify sources of water in the environment",
    "Learners describe the importance of water for life",
    "Learners practice water conservation and safe usage",
  ],
  "Personal Hygiene": [
    "Learners demonstrate proper hand washing and dental care",
    "Learners maintain personal cleanliness and grooming",
    "Learners develop lifelong healthy hygiene habits",
  ],
  Creation: [
    "Learners appreciate the wonders of creation in nature",
    "Learners describe the order and purpose in the natural world",
    "Learners demonstrate gratitude and care for creation",
  ],
  "Faith and Beliefs": [
    "Learners express understanding of their faith and beliefs",
    "Learners respect diverse religious beliefs and practices",
    "Learners demonstrate values derived from faith traditions",
  ],
  "Moral Values": [
    "Learners demonstrate honesty, kindness, and respect in actions",
    "Learners take responsibility for their choices and behavior",
    "Learners practice forgiveness and empathy in relationships",
  ],
  "Worship and Rituals": [
    "Learners participate in worship activities with reverence",
    "Learners describe the significance of religious rituals",
    "Learners appreciate the role of prayer in spiritual life",
  ],
  "Technical Skills": [
    "Learners identify and use basic tools and equipment safely",
    "Learners apply technical skills to create simple projects",
    "Learners demonstrate problem-solving through practical tasks",
  ],
  "Career Awareness": [
    "Learners identify different careers and their requirements",
    "Learners describe the skills needed for various occupations",
    "Learners set personal goals aligned with career interests",
  ],
  "Personal Health": [
    "Learners describe the components of a healthy lifestyle",
    "Learners practice physical fitness and personal wellness",
    "Learners make informed decisions about personal health",
  ],
  Nutrition: [
    "Learners classify foods according to their nutritional value",
    "Learners plan and prepare simple healthy meals",
    "Learners evaluate food choices for balanced nutrition",
  ],
  "Disease Prevention": [
    "Learners describe common diseases and their causes",
    "Learners practice preventive measures against diseases",
    "Learners demonstrate understanding of immunization and health screening",
  ],
  "Reproductive Health": [
    "Learners describe physical and emotional changes during adolescence",
    "Learners practice personal care and hygiene during development",
    "Learners demonstrate respect for themselves and others",
  ],
  "Substance Abuse": [
    "Learners identify harmful substances and their effects",
    "Learners develop resistance skills against peer pressure",
    "Learners make healthy choices regarding substance use",
  ],
  God: [
    "Learners express understanding of God as creator",
    "Learners appreciate God's love and care in daily life",
    "Learners demonstrate gratitude and reverence through prayer",
  ],
  Family: [
    "Learners describe roles and responsibilities of family members",
    "Learners demonstrate love, respect, and cooperation in the family",
    "Learners contribute positively to family activities",
  ],
  Community: [
    "Learners identify different groups and roles in the community",
    "Learners participate in community service activities",
    "Learners demonstrate responsibility towards community well-being",
  ],
  Culture: [
    "Learners describe cultural practices and traditions in their community",
    "Learners participate in cultural events with appreciation",
    "Learners respect and value cultural diversity",
  ],
  Time: [
    "Learners tell time using analog and digital clocks",
    "Learners organize daily activities according to time schedules",
    "Learners demonstrate punctuality and time management skills",
  ],
  Money: [
    "Learners identify Kenyan currency and its value",
    "Learners perform simple monetary transactions",
    "Learners practice responsible spending and saving habits",
  ],
  "Natural Resources": [
    "Learners identify natural resources in Kenya",
    "Learners describe sustainable use of natural resources",
    "Learners participate in conservation of natural resources",
  ],
  "Force and Motion": [
    "Learners describe the effects of forces on objects",
    "Learners demonstrate understanding of motion and direction",
    "Learners apply concepts of force in simple machines",
  ],
  Materials: [
    "Learners identify properties of different materials",
    "Learners classify materials based on their characteristics",
    "Learners select appropriate materials for specific purposes",
  ],
  Technology: [
    "Learners identify simple technological tools in daily use",
    "Learners use digital devices responsibly for learning",
    "Learners demonstrate awareness of technology in society",
  ],
  "Scientific Investigation": [
    "Learners make observations and ask questions about phenomena",
    "Learners conduct simple experiments following procedures",
    "Learners record and communicate findings from investigations",
  ],
}

export const BIBLE_VERSES: BibleVerse[] = [
  { ref: "Proverbs 1:7", text: "The fear of the Lord is the beginning of knowledge", explanation: "This verse teaches that reverence for God is the foundation of all true learning, connecting wisdom with humility." },
  { ref: "Proverbs 2:6", text: "For the Lord gives wisdom; from his mouth come knowledge and understanding", explanation: "This verse reminds us that all wisdom and understanding ultimately come from God, making Him the source of true education." },
  { ref: "Proverbs 9:10", text: "The fear of the Lord is the beginning of wisdom, and knowledge of the Holy One is understanding", explanation: "This verse reinforces that wisdom begins with reverence for God and that knowing Him leads to true understanding." },
  { ref: "Proverbs 22:6", text: "Train up a child in the way he should go; even when he is old he will not depart from it", explanation: "This verse emphasizes the importance of early instruction and the lasting impact of godly teaching and mentorship." },
  { ref: "Psalm 119:66", text: "Teach me knowledge and good judgment, for I trust your commands", explanation: "This verse connects the pursuit of knowledge and good judgment with trust in God's guidance." },
  { ref: "Psalm 32:8", text: "I will instruct you and teach you in the way you should go", explanation: "This verse assures that God is our ultimate teacher, guiding us in the right path." },
  { ref: "Isaiah 54:13", text: "All your children shall be taught by the Lord, and great shall be the peace of your children", explanation: "This verse promises that when children are taught by the Lord, they will experience great peace." },
  { ref: "Deuteronomy 6:7", text: "You shall teach them diligently to your children", explanation: "This verse calls for the faithful and diligent teaching of God's ways to the next generation." },
  { ref: "2 Timothy 3:16", text: "All Scripture is breathed out by God and profitable for teaching, for reproof, for correction", explanation: "This verse affirms the divine origin and practical value of Scripture for teaching and training in righteousness." },
  { ref: "Matthew 5:14", text: "You are the light of the world. A city set on a hill cannot be hidden", explanation: "This verse encourages learners to be positive influences in their communities, shining as examples of good character." },
  { ref: "Colossians 3:23", text: "Whatever you do, work heartily, as for the Lord and not for men", explanation: "This verse teaches diligence and wholehearted effort in all tasks, connecting work with service to God." },
  { ref: "James 1:5", text: "If any of you lacks wisdom, let him ask God, who gives generously", explanation: "This verse encourages learners to seek wisdom from God, who gives freely to all who ask." },
  { ref: "Proverbs 18:15", text: "An intelligent heart acquires knowledge, and the ear of the wise seeks knowledge", explanation: "This verse highlights the value of an eager mind that actively seeks knowledge and understanding." },
  { ref: "Luke 6:40", text: "A disciple is not above his teacher, but everyone when he is fully trained will be like his teacher", explanation: "This verse underscores the influence of a teacher and the transformative goal of education." },
  { ref: "Genesis 2:15", text: "The Lord God took the man and put him in the Garden of Eden to work it and keep it", explanation: "This verse teaches stewardship and responsible care of God's creation, aligning with environmental conservation." },
  { ref: "Proverbs 11:3", text: "The integrity of the upright guides them, but the crookedness of the treacherous destroys them", explanation: "This verse connects integrity with guidance and warns against dishonesty." },
  { ref: "Matthew 5:9", text: "Blessed are the peacemakers, for they shall be called sons of God", explanation: "This verse blesses those who work for peace, encouraging conflict resolution and harmony." },
  { ref: "Proverbs 10:9", text: "Whoever walks in integrity walks securely, but he who makes his ways crooked will be found out", explanation: "This verse teaches that integrity leads to security and that dishonesty is ultimately exposed." },
  { ref: "1 Corinthians 13:4-7", text: "Love is patient and kind; love does not envy or boast; it is not arrogant", explanation: "This passage defines love as patient, kind, and selfless, forming the foundation of healthy relationships." },
  { ref: "Psalm 133:1", text: "Behold, how good and pleasant it is when brothers dwell in unity", explanation: "This verse celebrates the beauty of unity and harmony among people." },
  { ref: "Philippians 2:3", text: "Do nothing from selfish ambition or conceit, but in humility count others more significant than yourselves", explanation: "This verse teaches humility and respect for others, placing their needs above our own." },
  { ref: "Mark 10:45", text: "For even the Son of Man came not to be served but to serve, and to give his life as a ransom for many", explanation: "This verse exemplifies servant leadership, teaching that true greatness comes through serving others." },
  { ref: "Exodus 20:12", text: "Honor your father and your mother, that your days may be long in the land", explanation: "This commandment teaches respect for parents and authority figures." },
  { ref: "Leviticus 19:18", text: "You shall love your neighbor as yourself", explanation: "This verse teaches love for others as a fundamental moral duty." },
  { ref: "Micah 6:8", text: "He has told you, O man, what is good; and what does the Lord require of you but to do justice, and to love kindness", explanation: "This verse summarizes God's requirements: justice, kindness, and walking humbly with God." },
  { ref: "Galatians 5:22-23", text: "The fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control", explanation: "This passage lists the virtues that form good character, aligning with values education." },
  { ref: "Romans 12:10", text: "Love one another with brotherly affection. Outdo one another in showing honor", explanation: "This verse encourages mutual respect, honor, and genuine care for others." },
  { ref: "Ephesians 4:32", text: "Be kind to one another, tenderhearted, forgiving one another, as God in Christ forgave you", explanation: "This verse teaches kindness, compassion, and forgiveness as essential Christian virtues." },
  { ref: "1 Corinthians 6:19", text: "Do you not know that your body is a temple of the Holy Spirit within you?", explanation: "This verse teaches that our bodies are sacred and should be treated with respect and care." },
  { ref: "Proverbs 22:3", text: "The prudent sees danger and hides himself, but the simple go on and suffer for it", explanation: "This verse teaches wisdom and caution, encouraging learners to make safe and prudent choices." },
  { ref: "Philippians 4:13", text: "I can do all things through him who strengthens me", explanation: "This verse teaches that true strength and ability come from God, encouraging confidence and perseverance." },
  { ref: "Revelation 7:9", text: "Before me was a great multitude that no one could count, from every nation, tribe, people and language", explanation: "This verse reveals the beauty of diversity, showing that people from every culture are valued by God." },
  { ref: "Luke 16:11", text: "If then you have not been faithful in the unrighteous wealth, who will entrust to you the true riches?", explanation: "This verse teaches that faithfulness in handling material resources reflects our character and trustworthiness." },
  { ref: "Exodus 20:12", text: "Honor your father and your mother, that your days may be long in the land", explanation: "This commandment teaches respect for parents and authority, forming the foundation of family life." },
  { ref: "Leviticus 19:18", text: "You shall love your neighbor as yourself", explanation: "This verse teaches love for others as a fundamental moral duty and the basis for healthy relationships." },
]

export const VERSE_MAP_BY_STRAND: Record<string, VerseSuggestion> = {
  Environment: {
    verseRef: "Genesis 2:15",
    connection: "This lesson on environmental conservation reinforces stewardship, responsibility, and care for creation.",
    explanation: "The verse teaches that humanity is entrusted with caring for God's creation, making environmental stewardship a sacred duty.",
  },
  "Living Things": {
    verseRef: "Genesis 2:15",
    connection: "This lesson on living things reinforces respect for God's creation and our responsibility to care for all forms of life.",
    explanation: "The verse reminds us that all living things are part of God's creation and deserve our care and respect.",
  },
  "Natural Resources": {
    verseRef: "Genesis 2:15",
    connection: "This lesson on natural resources reinforces responsible use and stewardship of the resources God has provided.",
    explanation: "The verse teaches that we are placed on earth to work it and keep it, emphasizing sustainable use of resources.",
  },
  "People and Relationships": {
    verseRef: "1 Corinthians 13:4-7",
    connection: "This lesson on relationships reinforces love, patience, and kindness as foundations for healthy interactions.",
    explanation: "This passage defines love as patient, kind, and selfless, providing a biblical model for all relationships.",
  },
  "Political Systems and Governance": {
    verseRef: "Proverbs 11:3",
    connection: "This lesson on governance reinforces the importance of integrity and honesty in leadership.",
    explanation: "The verse connects integrity with guidance, teaching that upright leaders lead their communities well.",
  },
  "Peace and Conflict Resolution": {
    verseRef: "Matthew 5:9",
    connection: "This lesson on peace and conflict resolution reinforces the value of peacemaking and reconciliation.",
    explanation: "The verse blesses peacemakers, affirming that those who work for peace reflect God's character.",
  },
  "Moral Values": {
    verseRef: "Micah 6:8",
    connection: "This lesson on moral values reinforces justice, kindness, and humility as foundational virtues.",
    explanation: "The verse summarizes what God requires: doing justice, loving kindness, and walking humbly.",
  },
  "Community Life": {
    verseRef: "Psalm 133:1",
    connection: "This lesson on community life reinforces the beauty and importance of unity and harmony.",
    explanation: "The verse celebrates how good and pleasant it is when people live together in unity.",
  },
  "Faith and Beliefs": {
    verseRef: "Proverbs 9:10",
    connection: "This lesson on faith and beliefs reinforces that true wisdom begins with reverence for God.",
    explanation: "The verse teaches that the fear of the Lord is the beginning of wisdom, connecting faith with knowledge.",
  },
  Energy: {
    verseRef: "Colossians 3:23",
    connection: "This lesson on energy reinforces diligence and wholehearted effort in all tasks.",
    explanation: "The verse teaches us to work heartily in everything we do, as service to God.",
  },
  Numbers: {
    verseRef: "Proverbs 18:15",
    connection: "This lesson on numbers reinforces the value of an eager mind that actively seeks understanding.",
    explanation: "The verse highlights how an intelligent heart acquires knowledge and the ear of the wise seeks it.",
  },
  Measurement: {
    verseRef: "Proverbs 18:15",
    connection: "This lesson on measurement reinforces precision, accuracy, and the pursuit of knowledge.",
    explanation: "The verse encourages the acquisition of knowledge and understanding through careful attention.",
  },
  Algebra: {
    verseRef: "Proverbs 2:6",
    connection: "This lesson on Algebra reinforces that understanding and wisdom come from God as the ultimate source.",
    explanation: "The verse reminds us that God gives wisdom, knowledge, and understanding.",
  },
  "Listening and Speaking": {
    verseRef: "James 1:5",
    connection: "This lesson on communication reinforces the importance of seeking wisdom to speak and listen well.",
    explanation: "The verse encourages asking God for wisdom, which He gives generously.",
  },
  Reading: {
    verseRef: "2 Timothy 3:16",
    connection: "This lesson on reading reinforces the value of Scripture and written knowledge for instruction.",
    explanation: "The verse affirms that all Scripture is profitable for teaching, reproof, and correction.",
  },
  Writing: {
    verseRef: "Proverbs 22:6",
    connection: "This lesson on writing reinforces the importance of training and instruction that lasts a lifetime.",
    explanation: "The verse promises that early training leaves a lasting impact that endures into old age.",
  },
  "Health and Hygiene": {
    verseRef: "1 Corinthians 6:19",
    connection: "This lesson on health reinforces that our bodies are sacred and should be cared for respectfully.",
    explanation: "The verse teaches that our bodies are temples of the Holy Spirit, calling us to care for them.",
  },
  Safety: {
    verseRef: "Proverbs 22:3",
    connection: "This lesson on safety reinforces prudence, caution, and wise decision-making.",
    explanation: "The verse teaches the importance of being alert to danger and taking appropriate precautions.",
  },
}

export const VERSE_MAP_BY_VALUE: Record<string, VerseSuggestion> = {
  Love: {
    verseRef: "1 Corinthians 13:4-7",
    connection: "This lesson's focus on love reinforces patience, kindness, and selflessness in relationships.",
    explanation: "This passage defines love as patient, kind, and not self-seeking, providing the biblical standard for love.",
  },
  Respect: {
    verseRef: "Philippians 2:3",
    connection: "This lesson's focus on respect reinforces humility and considering others as more important than ourselves.",
    explanation: "The verse teaches that true respect involves humility and valuing others above ourselves.",
  },
  Responsibility: {
    verseRef: "Colossians 3:23",
    connection: "This lesson's focus on responsibility reinforces working heartily and with dedication in all tasks.",
    explanation: "The verse teaches us to do everything with wholehearted effort, as working for the Lord.",
  },
  Unity: {
    verseRef: "Psalm 133:1",
    connection: "This lesson's focus on unity reinforces the beauty and strength of living together in harmony.",
    explanation: "The verse celebrates how good and pleasant unity is among people.",
  },
  Integrity: {
    verseRef: "Proverbs 10:9",
    connection: "This lesson's focus on integrity reinforces walking securely through honest and upright living.",
    explanation: "The verse teaches that integrity leads to security and a clear conscience before God.",
  },
  Peace: {
    verseRef: "Matthew 5:9",
    connection: "This lesson's focus on peace reinforces the blessedness of peacemaking and reconciliation.",
    explanation: "The verse blesses peacemakers, calling them children of God.",
  },
  Patriotism: {
    verseRef: "Exodus 20:12",
    connection: "This lesson's focus on patriotism reinforces honoring our nation and its institutions.",
    explanation: "The verse teaches honor and respect, which extends to our nation and community.",
  },
  "Self-Efficacy": {
    verseRef: "Philippians 4:13",
    connection: "This lesson's focus on self-efficacy reinforces confidence through God's strength.",
    explanation: "The verse teaches that true confidence comes from God who strengthens us.",
  },
}

export const VERSE_MAP_BY_SUBSTRAND: Record<string, VerseSuggestion> = {
  Family: {
    verseRef: "Exodus 20:12",
    connection: "This lesson on family reinforces honor, respect, and love within family relationships.",
    explanation: "The commandment to honor parents establishes the foundation for healthy family life.",
  },
  Community: {
    verseRef: "Psalm 133:1",
    connection: "This lesson on community reinforces unity, cooperation, and mutual support.",
    explanation: "The verse celebrates the beauty of people living together in harmony.",
  },
  "Belief in God": {
    verseRef: "Proverbs 9:10",
    connection: "This lesson on belief in God reinforces that true wisdom begins with reverence for God.",
    explanation: "The verse teaches that the fear of the Lord is the foundation of knowledge and wisdom.",
  },
  Honesty: {
    verseRef: "Proverbs 11:3",
    connection: "This lesson on honesty reinforces that integrity guides and protects those who walk uprightly.",
    explanation: "The verse teaches that honesty and integrity provide guidance and security.",
  },
  Environment: {
    verseRef: "Genesis 2:15",
    connection: "This lesson on the environment reinforces stewardship and responsible care of God's creation.",
    explanation: "The verse teaches that we are placed on earth to care for and keep it.",
  },
  Culture: {
    verseRef: "Revelation 7:9",
    connection: "This lesson on culture reinforces respect for diversity and the value of every culture.",
    explanation: "The verse reveals God's heart for all nations and cultures, showing the value of diversity.",
  },
  Money: {
    verseRef: "Luke 16:11",
    connection: "This lesson on money reinforces faithfulness, integrity, and wise stewardship of resources.",
    explanation: "The verse teaches that faithfulness in handling money reflects our character.",
  },
}

export const CURRICULUM_CONNECTION_MAP: Record<string, string> = {
  Environment: "Environmental conservation reinforces stewardship, responsibility, and care for God's creation.",
  "Living Things": "the study of living things reinforces respect for all forms of life as part of God's creation.",
  "Natural Resources": "the responsible use of natural resources reinforces our duty as stewards of God's provision.",
  "People and Relationships": "relationships reinforce love, patience, kindness, and mutual respect.",
  "Political Systems and Governance": "governance and leadership reinforce the importance of integrity and justice.",
  "Peace and Conflict Resolution": "peace education reinforces the value of peacemaking, reconciliation, and harmony.",
  "Moral Values": "moral values reinforce the biblical foundations of justice, kindness, and humility.",
  "Community Life": "community life reinforces the beauty of unity, cooperation, and mutual support.",
  "Faith and Beliefs": "faith and beliefs reinforce that true wisdom begins with reverence for God.",
  Numbers: "mathematical concepts reinforce the order and precision of God's creation.",
  Measurement: "measurement reinforces precision, accuracy, and the value of careful observation.",
  Algebra: "algebra reinforces logical thinking and the beauty of patterns in God's creation.",
  "Listening and Speaking": "communication reinforces the importance of wise speech and careful listening.",
  Reading: "reading reinforces the value of written knowledge and the importance of instruction.",
  Writing: "writing reinforces the importance of diligent practice and clear expression.",
}

export const VALUES_ADVISORY_ALL: string[] = [
  "Love", "Respect", "Responsibility", "Unity", "Integrity", "Peace", "Patriotism", "Self-Efficacy",
]

export const initialPlan: KICDPlan = {
  grade: "",
  learningArea: "",
  strand: "",
  subStrand: "",
  lessonNumber: "",
  duration: "",
  schoolName: "",
  teacherName: "",
  lessonDate: "",
  term: "",
  week: "",
  topicTitle: "",
  outcomes: [],
  successCriteria: [],
  keyInquiryQuestion: "",
  competencies: [],
  values: [],
  pcis: [],
  teacherActivities: [],
  learnerActivities: [],
  resources: [],
  assessmentMethods: [],
  remarks: "",
  lessonDevelopment: "",
  customGrades: [],
  customLearningAreas: [],
  customStrands: [],
  customSubStrands: [],
}
