"use client"

import React from "react"
import ReactMarkdown from "react-markdown"
import remarkGfm from "remark-gfm"
import rehypeRaw from "rehype-raw"
import type { FeatureDef } from "../types"

interface OutputViewerProps {
  output: string
  htmlOutput?: string
  showOutput: boolean
  feature: FeatureDef | undefined
  outputRef: React.RefObject<HTMLDivElement | null>
}

export default function OutputViewer({ output, htmlOutput, showOutput, feature, outputRef }: OutputViewerProps) {
  if (!showOutput) return null

  return (
    <div ref={outputRef} className="space-y-3">
      <div className="flex items-center gap-2 px-1">
        <div className="h-2 w-2 rounded-full bg-primary" />
        <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
          {feature?.name || "Document"}
        </span>
      </div>
      <div className="rounded-2xl border border-border/30 bg-white shadow-sm overflow-hidden dark:bg-card/90">
        <div className="border-b border-border/20 bg-gradient-to-r from-primary/5 to-primary/10 dark:from-primary/10 dark:to-primary/5 px-5 py-3">
          <div className="flex items-center gap-2">
            <span className="text-xs font-bold text-primary dark:text-primary uppercase tracking-wider">
              Kenya Institute of Curriculum Development
            </span>
          </div>
          <p className="text-[10px] text-muted-foreground/60 mt-0.5">
            Competency Based Curriculum &mdash; CBC Document
          </p>
        </div>
        <div className="p-5 sm:p-7 max-w-none ai-output text-sm leading-relaxed text-foreground/90">
          {htmlOutput ? (
            <div dangerouslySetInnerHTML={{ __html: htmlOutput }} />
          ) : (
            <ReactMarkdown
              remarkPlugins={[remarkGfm]}
              rehypePlugins={[rehypeRaw]}
              components={{
                h1({ children }) {
                  return <h1 className="text-lg font-bold text-foreground mt-6 mb-3 pb-2 border-b border-border/20">{children}</h1>
                },
                h2({ children }) {
                  return <h2 className="text-base font-bold text-foreground mt-5 mb-2">{children}</h2>
                },
                h3({ children }) {
                  return <h3 className="text-sm font-semibold text-foreground/90 mt-4 mb-1.5">{children}</h3>
                },
                table({ children }) {
                  return (
                    <div className="overflow-x-auto my-4 rounded-lg border border-border/20">
                      <table className="w-full border-collapse text-xs">{children}</table>
                    </div>
                  )
                },
                th({ children }) {
                  return <th className="border-b border-border/20 bg-muted/30 px-3 py-2.5 text-left font-semibold text-muted-foreground">{children}</th>
                },
                td({ children }) {
                  return <td className="border-b border-border/10 px-3 py-2.5 text-foreground/80">{children}</td>
                },
                pre({ children }) {
                  return (
                    <pre className="overflow-x-auto rounded-lg bg-muted/40 p-4 text-xs leading-relaxed font-mono border border-border/10">
                      {children}
                    </pre>
                  )
                },
                ul({ children }) {
                  return <ul className="list-disc pl-5 space-y-1 my-2">{children}</ul>
                },
                ol({ children }) {
                  return <ol className="list-decimal pl-5 space-y-1 my-2">{children}</ol>
                },
                blockquote({ children }) {
                  return <blockquote className="border-l-3 border-primary/40 pl-4 italic text-muted-foreground my-3">{children}</blockquote>
                },
                img({ src, alt }) {
                  return (
                    <img
                      src={src}
                      alt={alt || ""}
                      className="rounded-lg max-w-full h-auto my-3 border border-border/10"
                      loading="lazy"
                    />
                  )
                },
                p({ children }) {
                  return <p className="mb-3 leading-relaxed">{children}</p>
                },
                strong({ children }) {
                  return <strong className="font-semibold text-foreground">{children}</strong>
                },
              }}
            >
              {output}
            </ReactMarkdown>
          )}
        </div>
        <div className="border-t border-border/20 px-5 py-2.5 flex items-center justify-between">
          <span className="text-[10px] text-muted-foreground/40">Generated by Smart Tools Kit</span>
          <span className="text-[10px] text-muted-foreground/40">KICD &middot; CBC</span>
        </div>
      </div>
    </div>
  )
}
