"use client"

import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"

// ── Page layout ────────────────────────────────────────
const PW = 210
const PH = 297
const ML = 15
const MR = 15
const MT = 15
const MB = 24
const CW = PW - ML - MR

// ── Helpers ────────────────────────────────────────────

function typeLabel(id: string): string {
  const m: Record<string, string> = {
    "lesson-planner": "LESSON PLAN",
    "scheme-of-work": "SCHEME OF WORK",
    "assessment": "COMPETENCY-BASED ASSESSMENT",
    "comment-generator": "TEACHER COMMENT",
    "revision-planner": "REVISION PLAN",
    "generate-bulk-comments": "BULK COMMENTS",
    "education-followup": "FOLLOW-UP DOCUMENT",
  }
  return m[id] || "CBC DOCUMENT"
}

function docTitle(id: string): string {
  const m: Record<string, string> = {
    "lesson-planner": "CBC Lesson Plan",
    "scheme-of-work": "CBC Scheme of Work",
    "assessment": "CBC Assessment",
    "comment-generator": "CBC Teacher Comment",
    "revision-planner": "CBC Revision Plan",
    "generate-bulk-comments": "CBC Bulk Comments",
    "education-followup": "CBC Document",
  }
  return m[id] || "CBC Document"
}

function fmtDate(d: Date): string {
  const p = (n: number) => String(n).padStart(2, "0")
  return `${p(d.getDate())}/${p(d.getMonth() + 1)}/${d.getFullYear()} ${p(d.getHours())}:${p(d.getMinutes())}`
}

function strip(md: string): string {
  return md
    .replace(/\*\*(.+?)\*\*/g, "$1")
    .replace(/\*(.+?)\*/g, "$1")
    .replace(/~~(.+?)~~/g, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/!\[([^\]]*)\]\([^)]+\)/g, "($1)")
}

// ── Markdown block parser ──────────────────────────────

interface Block {
  t: "h1" | "h2" | "h3" | "h4" | "p" | "ul" | "ol" | "table" | "blockquote" | "code" | "hr"
  c: string
  items?: string[]
  rows?: string[][]
  code?: string[]
}

function parse(md: string): Block[] {
  const out: Block[] = []
  const lines = md.split("\n")
  let i = 0
  while (i < lines.length) {
    const l = lines[i]
    const t = l.trim()
    if (!t) { i++; continue }

    const hm = t.match(/^(#{1,4})\s+(.+)/)
    if (hm) { out.push({ t: `h${hm[1].length}` as Block["t"], c: strip(hm[2]) }); i++; continue }

    if (t.startsWith("|")) {
      const rows: string[][] = []
      const sep = i + 1 < lines.length && /^\|[\s\-:]+\|$/.test(lines[i + 1].trim())
      rows.push(t.split("|").map((x) => x.trim()).filter(Boolean))
      i++
      if (sep) i++
      while (i < lines.length && lines[i].trim().startsWith("|")) {
        const c = lines[i].trim().split("|").map((x) => x.trim()).filter(Boolean)
        if (c.length) rows.push(c)
        i++
      }
      out.push({ t: "table", c: "", rows })
      continue
    }

    if (/^[-*]\s/.test(t) || /^\d+[.)]\s/.test(t)) {
      const items: string[] = []
      const ord = /^\d+[.)]\s/.test(t)
      while (i < lines.length) {
        const lt = lines[i].trim()
        if (/^[-*]\s/.test(lt) || /^\d+[.)]\s/.test(lt)) {
          items.push(strip(lt.replace(/^[-*]\s+/, "").replace(/^\d+[.)]\s+/, "")))
          i++
        } else { break }
      }
      out.push({ t: ord ? "ol" : "ul", c: "", items })
      continue
    }

    if (t.startsWith(">")) {
      const q: string[] = []
      while (i < lines.length && lines[i].trim().startsWith(">")) {
        q.push(lines[i].trim().replace(/^>\s*/, ""))
        i++
      }
      out.push({ t: "blockquote", c: strip(q.join(" ")) })
      continue
    }

    if (t.startsWith("```")) {
      const code: string[] = []
      i++
      while (i < lines.length && !lines[i].trim().startsWith("```")) {
        code.push(lines[i])
        i++
      }
      i++
      out.push({ t: "code", c: "", code })
      continue
    }

    if (/^---/.test(t)) { out.push({ t: "hr", c: "" }); i++; continue }

    out.push({ t: "p", c: strip(t) })
    i++
  }
  return out
}

// ── Footer ─────────────────────────────────────────────

function drawFooter(doc: jsPDF, pageNum: number, title: string, date: string): void {
  const fy = PH - MB + 5
  doc.setDrawColor(200, 200, 200)
  doc.setLineWidth(0.4)
  doc.line(ML, fy - 3, PW - MR, fy - 3)

  doc.setFontSize(7)
  doc.setTextColor(150, 150, 150)
  doc.setFont("helvetica", "normal")
  doc.text("Generated by Smart Tools Kit", ML, fy + 2, { align: "left" })
  doc.text(title, PW / 2, fy + 2, { align: "center" })
  doc.text(`Page ${pageNum}`, PW - MR, fy + 2, { align: "right" })

  doc.setFontSize(8)
  doc.setTextColor(180, 180, 180)
  doc.text(date, PW / 2, fy - 2, { align: "center" })
}

// ── Header ─────────────────────────────────────────────

function drawHeader(doc: jsPDF, featureId: string, ctx: Record<string, string>): number {
  let y = MT + 2

  doc.setFontSize(14)
  doc.setFont("helvetica", "bold")
  doc.text("KENYA INSTITUTE OF CURRICULUM DEVELOPMENT", PW / 2, y, { align: "center" })
  y += 7

  doc.setFontSize(9)
  doc.setFont("helvetica", "normal")
  doc.text("COMPETENCY-BASED CURRICULUM (CBC)", PW / 2, y, { align: "center" })
  y += 5

  doc.setFontSize(13)
  doc.setFont("helvetica", "bold")
  doc.setTextColor(37, 99, 235)
  doc.text(typeLabel(featureId), PW / 2, y, { align: "center" })
  doc.setTextColor(0, 0, 0)
  y += 7

  doc.setDrawColor(30, 58, 95)
  doc.setLineWidth(0.6)
  doc.line(ML, y, PW - MR, y)
  y += 5

  doc.setFillColor(248, 250, 252)
  doc.roundedRect(ML, y, CW, 55, 1.5, 1.5, "F")
  y += 1.5

  const fields: [string, string][] = [
    ["School", "_____________________________"],
    ["Teacher", "_____________________________"],
    ["Term", "_____________________________"],
    ["Week", "_____________________________"],
    ["Date", "_____________________________"],
    ["Learning Area", ctx["learningArea"] || "_____________________________"],
    ["Grade", ctx["grade"] || "_____________________________"],
    ["Strand", ctx["strand"] || "_____________________________"],
    ["Sub-Strand", ctx["subStrand"] || "_____________________________"],
    ["Lesson Duration", ctx["duration"] ? `${ctx["duration"]} Minutes` : "_____________________________"],
  ]

  doc.setFontSize(9)
  for (const [label, value] of fields) {
    doc.setFont("helvetica", "bold")
    doc.text(label + ":", ML + 4, y + 3.5)
    doc.setFont("helvetica", "normal")
    doc.text(value, ML + 42, y + 3.5)
    y += 5.2
  }

  y += 4
  return y
}

// ── Content renderers ──────────────────────────────────

function renderHeading(doc: jsPDF, text: string, level: number, x: number, y: number): number {
  const sizes: Record<number, number> = { 1: 15, 2: 13, 3: 11, 4: 10 }
  const colors: Record<number, [number, number, number]> = {
    1: [26, 54, 93],
    2: [30, 58, 95],
    3: [37, 99, 235],
    4: [37, 99, 235],
  }
  const fs = sizes[level] || 10
  const color = colors[level] || [0, 0, 0]

  doc.setFontSize(fs)
  doc.setFont("helvetica", "bold")
  doc.setTextColor(...color)
  doc.text(text, x, y)
  doc.setTextColor(0, 0, 0)

  const lineSpacing = fs * 0.35
  if (level <= 2) {
    doc.setDrawColor(37, 99, 235)
    doc.setLineWidth(0.5)
    doc.line(x, y + 1.5, PW - MR, y + 1.5)
  }

  return y + lineSpacing + 3
}

function renderParagraph(doc: jsPDF, text: string, x: number, y: number, maxW: number): number {
  doc.setFontSize(10)
  doc.setFont("helvetica", "normal")
  const lines = doc.splitTextToSize(text, maxW)
  for (const line of lines) {
    if (y > PH - MB - 5) {
      return -1
    }
    doc.text(line as string, x, y)
    y += 4.5
  }
  return y + 2
}

function renderList(doc: jsPDF, items: string[], ordered: boolean, x: number, y: number, maxW: number): number {
  doc.setFontSize(10)
  doc.setFont("helvetica", "normal")
  const indent = 5
  let i = 0
  for (const item of items) {
    if (y > PH - MB - 5) {
      return -1
    }
    i++
    const prefix = ordered ? `${i}.` : "\u2022"
    doc.text(`${prefix} ${item}`, x + indent, y)
    y += 4.5
  }
  return y + 2
}

function renderBlockquote(doc: jsPDF, text: string, x: number, y: number, maxW: number): number {
  doc.setDrawColor(37, 99, 235)
  doc.setLineWidth(0.6)
  doc.line(x, y - 3, x, y + 10)

  doc.setFontSize(10)
  doc.setFont("helvetica", "italic")
  doc.setTextColor(100, 100, 100)
  const lines = doc.splitTextToSize(text, maxW - 6)
  for (const line of lines) {
    if (y > PH - MB - 5) {
      return -1
    }
    doc.text(line as string, x + 4, y)
    y += 4.5
  }
  doc.setTextColor(0, 0, 0)
  return y + 2
}

function renderCode(doc: jsPDF, code: string[], x: number, y: number, maxW: number): number {
  doc.setFillColor(245, 245, 245)
  const lineH = 3.8
  const h = code.length * lineH + 6
  doc.roundedRect(x, y - 2, maxW, h, 1, 1, "F")

  doc.setFontSize(8)
  doc.setFont("courier", "normal")
  doc.setTextColor(60, 60, 60)
  for (const line of code) {
    if (y > PH - MB - 5) {
      return -1
    }
    doc.text(line, x + 4, y + 2)
    y += lineH
  }
  doc.setTextColor(0, 0, 0)
  return y + 2
}

// ── Main export ────────────────────────────────────────

export async function exportPdf(
  markdown: string,
  filename: string,
  docTitleParam?: string,
  featureId?: string,
  settings?: Record<string, string>,
): Promise<void> {
  const fid = featureId || "lesson-planner"
  const title = docTitle(fid)
  const date = fmtDate(new Date())
  const ctx = settings || {}

  const doc = new jsPDF("p", "mm", "a4")
  const blocks = parse(markdown)

  let y = drawHeader(doc, fid, ctx)
  let curPage = 1

  function need(mm: number): void {
    if (y + mm > PH - MB) {
      drawFooter(doc, curPage, title, date)
      doc.addPage()
      curPage++
      y = MT + 2
    }
  }

  for (const block of blocks) {
    switch (block.t) {
      case "h1": { need(10); y = renderHeading(doc, block.c, 1, ML, y); break }
      case "h2": { need(8); y = renderHeading(doc, block.c, 2, ML, y); break }
      case "h3": { need(7); y = renderHeading(doc, block.c, 3, ML, y); break }
      case "h4": { need(6); y = renderHeading(doc, block.c, 4, ML, y); break }

      case "p": {
        need(5)
        const result = renderParagraph(doc, block.c, ML, y, CW)
        if (result === -1) {
          drawFooter(doc, curPage, title, date)
          doc.addPage()
          curPage++
          y = MT + 2
          const r2 = renderParagraph(doc, block.c, ML, y, CW)
          if (r2 !== -1) y = r2
        } else {
          y = result
        }
        break
      }

      case "ul":
      case "ol": {
        const items = block.items || []
        const estH = items.length * 5 + 3
        need(estH)
        const result = renderList(doc, items, block.t === "ol", ML, y, CW)
        if (result === -1) {
          drawFooter(doc, curPage, title, date)
          doc.addPage()
          curPage++
          y = MT + 2
          const r2 = renderList(doc, items, block.t === "ol", ML, y, CW)
          if (r2 !== -1) y = r2
        } else {
          y = result
        }
        break
      }

      case "blockquote": {
        need(8)
        const result = renderBlockquote(doc, block.c, ML, y, CW)
        if (result === -1) {
          drawFooter(doc, curPage, title, date)
          doc.addPage()
          curPage++
          y = MT + 2
          const r2 = renderBlockquote(doc, block.c, ML, y, CW)
          if (r2 !== -1) y = r2
        } else {
          y = result
        }
        break
      }

      case "code": {
        const lines = block.code || []
        const estH = lines.length * 4 + 6
        need(estH)
        const result = renderCode(doc, lines, ML, y, CW)
        if (result === -1) {
          drawFooter(doc, curPage, title, date)
          doc.addPage()
          curPage++
          y = MT + 2
          const r2 = renderCode(doc, lines, ML, y, CW)
          if (r2 !== -1) y = r2
        } else {
          y = result
        }
        break
      }

      case "hr": {
        need(4)
        doc.setDrawColor(200, 200, 200)
        doc.setLineWidth(0.4)
        doc.line(ML, y, PW - MR, y)
        y += 4
        break
      }

      case "table": {
        const rows = block.rows || []
        if (rows.length === 0) break

        drawFooter(doc, curPage, title, date)

        const hasHeader = rows.length >= 2
        const headRows = hasHeader ? [rows[0]] : undefined
        const bodyRows = hasHeader ? rows.slice(1) : rows

        autoTable(doc, {
          startY: y,
          head: headRows,
          body: bodyRows,
          margin: { left: ML, right: MR },
          tableWidth: "auto",
          theme: "striped",
          headStyles: {
            fillColor: [30, 58, 95],
            textColor: 255,
            fontStyle: "bold",
            fontSize: 9,
            halign: "left",
          },
          bodyStyles: {
            fontSize: 9,
            textColor: [51, 51, 51],
            lineColor: [200, 200, 200],
            lineWidth: 0.2,
          },
          alternateRowStyles: {
            fillColor: [248, 250, 252],
          },
          styles: {
            cellPadding: { top: 2, bottom: 2, left: 3, right: 3 },
            overflow: "linebreak",
          },
          didDrawPage: (data) => {
            drawFooter(doc, data.pageNumber, title, date)
          },
        })

        const lastTbl = (doc as unknown as Record<string, unknown>).lastAutoTable as
          | { finalY: number }
          | undefined
        if (lastTbl && typeof lastTbl.finalY === "number") {
          y = lastTbl.finalY + 6
        } else {
          y += 10
        }

        curPage = doc.getCurrentPageInfo().pageNumber
        break
      }
    }
  }

  drawFooter(doc, curPage, title, date)
  doc.save(`${filename}.pdf`)
}
